### ISSUE TITLE
write integration tests for contracts 

### ISSUE THREAD

**Issue by maraoz** [maraoz/rewilder#26]
Unit tests use an Externally owned account (EOAs) as the rewilder wallet. Write integration tests where `_wallet` is a 2-of-3 Gnosis Safe (https://github.com/gnosis/safe-contracts) in [RewilderDonationCampaign's constructor](https://github.com/maraoz/rewilder/blob/dapp/contracts/RewilderDonationCampaign.sol#L16), and make sure everything works properly:
- campaign can be deployed and transfered to gnosis safe,
- random accounts can donate and receive NFTs
- gnosis safe can pause campaign
- when paused, donations revert
- gnosis safe can unpause campaign
- when unpaused, donations work again and mint NFTs
- gnosis safe can finalize campaign

**Comment by jparnaudo** [comment]
https://github.com/maraoz/rewilder/pull/90
